/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 08 12:15:58 GMT 2021
 */

package evoSuite;

import org.junit.Test;
import static org.junit.Assert.*;
import evoSuite.MyEvoSuite;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MyEvoSuite_ESTest extends MyEvoSuite_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MyEvoSuite myEvoSuite0 = new MyEvoSuite();
      int int0 = myEvoSuite0.add(0, 3544);
      assertEquals(3544, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MyEvoSuite myEvoSuite0 = new MyEvoSuite();
      int int0 = myEvoSuite0.add((-623), 0);
      assertEquals((-623), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MyEvoSuite myEvoSuite0 = new MyEvoSuite();
      int int0 = myEvoSuite0.add(0, 0);
      assertEquals(0, int0);
  }
}
