/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 14 08:25:10 GMT 2021
 */

package evoSuite;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertEquals;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MyEvoSuite_ESTest extends MyEvoSuite_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MyEvoSuite myEvoSuite0 = new MyEvoSuite();
      int int0 = myEvoSuite0.add(126, 0);
      assertEquals(126, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MyEvoSuite myEvoSuite0 = new MyEvoSuite();
      int int0 = myEvoSuite0.add((-1314), 126);
      assertEquals((-1188), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MyEvoSuite myEvoSuite0 = new MyEvoSuite();
      int int0 = myEvoSuite0.add(0, 0);
      assertEquals(0, int0);
  }
}
